FROM node:22.15.1-alpine

# Установка рабочей директории
WORKDIR /usr/src/app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем исходный код 
COPY . .
# Сборка приложения
RUN npm run build

EXPOSE 3001

CMD ["npm", "run", "start:prod"]
