---
config:
  theme: base
  look: classic
  layout: elk
---
flowchart TD
    A[Администратор] --> B[POST /api/v1/auth/login с логином и паролем в теле запроса]
    B --> C[Auth Service проверяет данные]
    C --> D{Успешно?}
    D -- Нет --> E[401 Unauthorized]
    D -- Да --> F[Генерация JWT токена]
    F --> G[Ответ: 200 OK + JWT]
    G --> H[Администратор использует токен в Authorization: Bearer <JWT>]