---
config:
  theme: base
  look: classic
  layout: elk
---
flowchart TD
    A[Frontend запрашивает JSON у PageService] --> B[PageService возвращает JSON с массивом компонентов]
    B --> C[Итерация по каждому компоненту из JSON]
    C --> D{Реестр компонентов содержит type?}
    
    D -- Да --> E[Получаем компонент из реестра]
    D -- Нет --> F[Динамический импорт компонента]
    F --> G[Реестр компонентов регистрирует новый компонент]
    G --> E
    
    E --> H[Универсальный рендерер создаёт React-элемент с props]
    H --> I[Добавляет компонент в дерево страницы]
    I --> J{Остались компоненты?}
    J -- Да --> C
    J -- Нет --> K[Результирующее дерево отрисовывается на экране]
