---
config:
  theme: base
  look: classic
  layout: elk
---
flowchart TD
    A[Разработчик создаёт компонент SomeComponent.tsx в /src/plugins] --> B[SomeComponent экспортирует default react-компонент]
    B --> C[Система плагинов обнаруживает файл]
    C --> D[Реестр компонентов мапит type SomeComponent и путь к файлу]
    
    E[Администратор добавляет блок в JSON] --> F[PageService возвращает JSON с этим блоком]
    
    F --> G[Frontend получает JSON]
    G --> H{Компонент SomeComponent зарегистрирован?}
    
    H -- Нет --> I[Реестр компонентов подгружает компонент динамически ]
    I --> J[Регистрирует компонент в реестре]
    
    H -- Да --> K[Создаёт компонент с props]
    J --> K
    
    K --> L[Рендерит компонент в UI]
